language: python

# the new trusty images of Travis cause build errors with psycopg2, see https://github.com/travis-ci/travis-ci/issues/8897
dist: trusty
group: deprecated-2017Q4

python:
    - "2.7"
env:
    - CKANVERSION=master
    - CKANVERSION=2.7
install:
    - bash bin/travis-build.bash
services:
    - postgresql
    - redis
addons:
    postgresql: "9.3"
script: sh bin/travis-run.sh
after_success: coveralls
sudo: required
